/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Query TypeMap
import '@sanity/client'

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Icon = {
  _type: 'icon'
  name?: string
}

export type TranslationMetadata = {
  _id: string
  _type: 'translation.metadata'
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: InternationalizedArrayReference
  schemaTypes?: Array<string>
}

export type InternationalizedArrayReference = Array<
  {
    _key: string
  } & InternationalizedArrayReferenceValue
>

export type HeroReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'hero'
}

export type MarqueeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'marquee'
}

export type ProjectOverviewReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'projectOverview'
}

export type ServicesGridReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'servicesGrid'
}

export type ButtonLinkReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'buttonLink'
}

export type PageBuilderReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'pageBuilder'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type SeoReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'seo'
}

export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue'
  value?:
    | HeroReference
    | MarqueeReference
    | ProjectOverviewReference
    | ServicesGridReference
    | ButtonLinkReference
    | PageBuilderReference
    | PageReference
    | ProjectReference
    | SeoReference
  language?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  keywords?: Array<string>
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  link?: string
  thumbnail?: {
    image?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    alt?: string
  }
  language?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type PageBuilder = Array<
  | ({
      _key: string
    } & Hero)
  | ({
      _key: string
    } & Marquee)
  | ({
      _key: string
    } & ProjectOverview)
  | ({
      _key: string
    } & ServicesGrid)
>

export type ButtonLink = {
  _type: 'buttonLink'
  label?: string
  link?: PageReference
  variant?:
    | 'default'
    | 'outline'
    | 'accent'
    | 'secondary'
    | 'ghost'
    | 'link'
    | 'destructive'
  size?: 'default' | 'sm' | 'lg' | 'xl' | 'icon' | 'icon-sm' | 'icon-lg'
  icon?: Icon
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  content?: PageBuilder
  seo?: Seo
  language?: string
}

export type ServicesGrid = {
  _type: 'servicesGrid'
  preTitle?: string
  title?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & ButtonLink)
  >
  services?: Array<{
    title?: string
    description?: string
    points?: Array<string>
    _key: string
  }>
}

export type ProjectOverview = {
  _type: 'projectOverview'
  title?: string
  projects?: Array<
    {
      _key: string
    } & ProjectReference
  >
}

export type Marquee = {
  _type: 'marquee'
  items?: Array<string>
}

export type Hero = {
  _type: 'hero'
  preTitleOne?: string
  preTitleTwo?: string
  title?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & ButtonLink)
  >
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & ButtonLink)
  >
  buttons?: Array<
    {
      _key: string
    } & ButtonLink
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | MediaTag
  | Slug
  | Icon
  | TranslationMetadata
  | InternationalizedArrayReference
  | HeroReference
  | MarqueeReference
  | ProjectOverviewReference
  | ServicesGridReference
  | ButtonLinkReference
  | PageBuilderReference
  | PageReference
  | ProjectReference
  | SeoReference
  | InternationalizedArrayReferenceValue
  | SanityImageAssetReference
  | Seo
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | PageBuilder
  | ButtonLink
  | Page
  | ServicesGrid
  | ProjectOverview
  | Marquee
  | Hero
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../web/app/utils/sanity-queries.ts
// Variable: pageQuery
// Query: *[    _type in ["page"] &&    slug.current == $slug &&    language == $language  ][0]{    ...,      content[]{    ...,    _type == "hero" => {      ...,      buttons[]{        ...,        "link": link->slug.current      }    },    _type == "projectOverview" => {      ...,      projects[]->{        _id,        title,        description,        category,        thumbnail,        link      }    },  },    "seo": {      "_type": "seo",      "title": coalesce(seo.title, ""),      "description": coalesce(seo.description,  ""),      "image": seo.image,      "keywords": coalesce(seo.keywords, []),    },  }
export type PageQueryResult = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  content: Array<
    | {
        _key: string
        _type: 'hero'
        preTitleOne?: string
        preTitleTwo?: string
        title?: Array<
          | ({
              _key: string
            } & ButtonLink)
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?:
                | 'blockquote'
                | 'h1'
                | 'h2'
                | 'h3'
                | 'h4'
                | 'h5'
                | 'h6'
                | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
        >
        description?: Array<
          | ({
              _key: string
            } & ButtonLink)
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?:
                | 'blockquote'
                | 'h1'
                | 'h2'
                | 'h3'
                | 'h4'
                | 'h5'
                | 'h6'
                | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
        >
        buttons: Array<{
          _key: string
          _type: 'buttonLink'
          label?: string
          link: string | null
          variant?:
            | 'accent'
            | 'default'
            | 'destructive'
            | 'ghost'
            | 'link'
            | 'outline'
            | 'secondary'
          size?: 'default' | 'icon-lg' | 'icon-sm' | 'icon' | 'lg' | 'sm' | 'xl'
          icon?: Icon
        }> | null
      }
    | {
        _key: string
        _type: 'marquee'
        items?: Array<string>
      }
    | {
        _key: string
        _type: 'projectOverview'
        title?: string
        projects: Array<{
          _id: string
          title: string | null
          description: string | null
          category: null
          thumbnail: {
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
            }
            alt?: string
          } | null
          link: string | null
        }> | null
      }
    | {
        _key: string
        _type: 'servicesGrid'
        preTitle?: string
        title?: Array<
          | ({
              _key: string
            } & ButtonLink)
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?:
                | 'blockquote'
                | 'h1'
                | 'h2'
                | 'h3'
                | 'h4'
                | 'h5'
                | 'h6'
                | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
        >
        services?: Array<{
          title?: string
          description?: string
          points?: Array<string>
          _key: string
        }>
      }
  > | null
  seo: {
    _type: 'seo'
    title: string | ''
    description: string | ''
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    keywords: Array<string> | Array<never>
  }
  language?: string
} | null
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[\n    _type in ["page"] &&\n    slug.current == $slug &&\n    language == $language\n  ][0]{\n    ...,\n    \n  content[]{\n    ...,\n    _type == "hero" => {\n      ...,\n      buttons[]{\n        ...,\n        "link": link->slug.current\n      }\n    },\n    _type == "projectOverview" => {\n      ...,\n      projects[]->{\n        _id,\n        title,\n        description,\n        category,\n        thumbnail,\n        link\n      }\n    },\n  },\n\n    "seo": {\n      "_type": "seo",\n      "title": coalesce(seo.title, ""),\n      "description": coalesce(seo.description,  ""),\n      "image": seo.image,\n      "keywords": coalesce(seo.keywords, []),\n    },\n  }\n': PageQueryResult
  }
}
